In [1]:
import numpy as np

## Creating the point A
A = np.array([1, 3, 5, 7, 13])
A

array([ 1,  3,  5,  7, 13])

In [5]:
## Min-Max normalization
(A - np.min(A)) / (np.max(A) - np.min(A))

array([0.        , 0.16666667, 0.33333333, 0.5       , 1.        ])

In [6]:
## Z-score standardization
(A - np.mean(A)) / np.std(A, ddof = 1)

array([-1.04249338, -0.60812114, -0.1737489 ,  0.26062335,  1.56374007])