In [1]:
import numpy as np

## creating the array
a = np.array([1, 3, 5, 7, 13])
a

array([ 1,  3,  5,  7, 13])

In [2]:
## min-max normalization
a_min = np.min(a)
a_max = np.max(a)
(a - a_min) / (a_max - a_min)

array([0.        , 0.16666667, 0.33333333, 0.5       , 1.        ])

In [3]:
## z-score standardization
a_mean = np.mean(a)
a_std = np.std(a, ddof = 1)
(a - a_mean) / a_std

array([-1.04249338, -0.60812114, -0.1737489 ,  0.26062335,  1.56374007])