# Loading Libraries

In [6]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline, Pipeline
from sklearn.multiclass import OneVsRestClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix

# Reading the data

In [7]:
iris = pd.read_csv('Iris.csv')
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [8]:
iris['Species'].value_counts(normalize = True)

Iris-setosa        0.333333
Iris-versicolor    0.333333
Iris-virginica     0.333333
Name: Species, dtype: float64

In [9]:
iris['Species'] = iris['Species'].map({'Iris-setosa': 1, 
                                       'Iris-versicolor': 2,
                                       'Iris-virginica': 3})
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        1
1   2            4.9           3.0            1.4           0.2        1
2   3            4.7           3.2            1.3           0.2        1
3   4            4.6           3.1            1.5           0.2        1
4   5            5.0           3.6            1.4           0.2        1

# Defining X and Y

In [10]:
X = iris[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']]
Y = iris['Species']

# Splitting the data 

In [11]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, stratify = Y)

# One-vs-all with Random Forest

In [13]:
RF_md = OneVsRestClassifier(estimator = make_pipeline(MinMaxScaler(), 
                                                      RandomForestClassifier(n_estimators = 500,
                                                                             max_depth = 3))).fit(X_train, Y_train)

RF_pred = RF_md.predict(X_test)

# Confusion matrix
print(confusion_matrix(Y_test, RF_pred))

[[10  0  0]
 [ 0  9  1]
 [ 0  3  7]]


# One-vs-all with SVM

In [14]:
svm_md = OneVsRestClassifier(estimator = make_pipeline(MinMaxScaler(), 
                                                       SVC(kernel = 'rbf',
                                                           C = 0.1))).fit(X_train, Y_train)

svm_pred = svm_md.predict(X_test)

# Confusion matrix
print(confusion_matrix(Y_test, svm_pred))

[[10  0  0]
 [ 0 10  0]
 [ 0  3  7]]


In [15]:
# Based on my results, I would use one-vs-rest with SVM to predict Species.