In [ ]:
# Exercise 1
# a, logistic regression is a parametric model while random forest is a non-parametric model

In [ ]:
# Exercise 2
# bagged prediction averages predictions. So, the bagged prediction is the averege (compute it)

In [ ]:
# Exercise 3
# In boosting, the trees are built sequentially from one another and rely on the informatino of the previous tree.
# In random forest, the trees are built independently.

In [ ]:
# Exercise 4
# Follow the logic of the trees. For example, for observation 1 Class is No.

In [3]:
# Exercise 5
import pandas as pd
import numpy  as np

from sklearn.ensemble import RandomForestClassifier

# Read csv file
credit_default = pd.read_csv('Default.csv')
credit_default.head()

default student      balance        income
0      No      No   729.526495  44361.625074
1      No     Yes   817.180407  12106.134700
2      No      No  1073.549164  31767.138947
3      No      No   529.250605  35704.493935
4      No      No   785.655883  38463.495879

In [4]:
# Creating default_numb
credit_default['default_numb'] = np.where(credit_default['default'] == 'No', 0, 1)

In [6]:
X = credit_default[['balance', 'income']]
Y = credit_default['default_numb']

# Building RF model
RF_md = RandomForestClassifier().fit(X, Y)

# Define the new observation
# new_obs = pd.DataFrame({'balance': [2,000], 'income': [70,000]})
new_obs = pd.DataFrame({'balance': [2000], 'income': [70000]})
new_obs

balance  income
0     2000   70000

In [7]:
# Predicting likelyhood of default
RF_md.predict_proba(new_obs)

array([[0.18, 0.82]])

In [8]:
# Creating student_numb
credit_default['student_numb'] = np.where(credit_default['student'] == 'No', 0, 1)

In [9]:
X = credit_default[['balance', 'income', 'student_numb']]
Y = credit_default['default_numb']

# Building RF model
RF_md = RandomForestClassifier().fit(X, Y)

# Define the new observation
new_obs2 = pd.DataFrame({'balance': [2500], 'income': [20000], 'student_numb': [1]})
new_obs2

balance  income  student_numb
0     2500   20000             1

In [10]:
# Predicting likelyhood of default
RF_md.predict_proba(new_obs2)

array([[0.03, 0.97]])

In [11]:
# Exercise 6

# Read csv file
churn = pd.read_csv('Churn_Data.csv')
churn.head()

CustomerId  CreditScore Geography  Gender  Age  Tenure    Balance  \
0    15634602          619    France  Female   42       2       0.00   
1    15647311          608     Spain  Female   41       1   83807.86   
2    15619304          502    France  Female   42       8  159660.80   
3    15701354          699    France  Female   39       1       0.00   
4    15737888          850     Spain  Female   43       2  125510.82   

   NumOfProducts  HasCreditCard  IsActiveMember  EstimatedSalary  Churn  
0              1              1               1        101348.88      1  
1              1              0               1        112542.58      0  
2              3              1               0        113931.57      1  
3              2              0               0         93826.63      0  
4              1              1               1         79084.10      0

In [12]:
# Creating Churn_numb (don't need this)
# churn['Churn_numb'] = np.where(churn['Churn'] == 'No', 0, 1)
# churn.head()

CustomerId  CreditScore Geography  Gender  Age  Tenure    Balance  \
0    15634602          619    France  Female   42       2       0.00   
1    15647311          608     Spain  Female   41       1   83807.86   
2    15619304          502    France  Female   42       8  159660.80   
3    15701354          699    France  Female   39       1       0.00   
4    15737888          850     Spain  Female   43       2  125510.82   

   NumOfProducts  HasCreditCard  IsActiveMember  EstimatedSalary  Churn  \
0              1              1               1        101348.88      1   
1              1              0               1        112542.58      0   
2              3              1               0        113931.57      1   
3              2              0               0         93826.63      0   
4              1              1               1         79084.10      0   

   Churn_numb  
0           1  
1           1  
2           1  
3           1  
4           1

In [12]:
# Defining the input and target variables
X = churn[['Age', 'EstimatedSalary', 'CreditScore', 'Balance', 'NumOfProducts']]
# Y = churn['Churn_numb']
Y = churn['Churn']

# {'n_estimators': [500], 'max_depth': [3]}

# Building RF model
# RF_md = RandomForestClassifier().fit(X, Y)
RF_md = RandomForestClassifier(n_estimators = 500, max_depth = 3).fit(X, Y)

# Define the new observation
new_obs3 = pd.DataFrame({'Age': [50], 'EstimatedSalary': [100000], 'CreditScore': [600], 'Balance': [100000], 'NumOfProducts': [2]})
new_obs3

Age  EstimatedSalary  CreditScore  Balance  NumOfProducts
0   50           100000          600   100000              2

In [13]:
# Predicting the likelihood of churn
RF_md.predict_proba(new_obs3)

array([[0.65045149, 0.34954851]])

In [14]:
from sklearn.ensemble import GradientBoostingClassifier

# Defining the input and target variables
X = churn[['Age', 'EstimatedSalary', 'CreditScore', 'Balance', 'NumOfProducts']]
# Y = churn['Churn_numb']
Y = churn['Churn']

# {'n_estimators': [500], 'max_depth': [3]}

# Building RF model
# GB_md = GradientBoostingClassifier().fit(X, Y)
GB_md = GradientBoostingClassifier(n_estimators = 500, max_depth = 3).fit(X, Y)

# Define the new observation
new_obs4 = pd.DataFrame({'Age': [50], 'EstimatedSalary': [100000], 'CreditScore': [600], 'Balance': [100000], 'NumOfProducts': [2]})
new_obs4

Age  EstimatedSalary  CreditScore  Balance  NumOfProducts
0   50           100000          600   100000              2

In [15]:
# Predicting likelyhood of churn
GB_md.predict_proba(new_obs4)

array([[0.73146357, 0.26853643]])